language: python
python:
  - "3.7"

env:
  - DJANGO=3.0.*
install:
  - pip install -q Django==$DJANGO
  - pip install coveralls
  - pip install -r requirements.txt


before_script:
  - flake8 . --config=flake8

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.0.*
    - python: "2.7"
      env: DJANGO=2.0.*