# Generated by Django 3.0.5 on 2020-04-03 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonenumber_confirmation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberconfirmation',
            name='pin',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(6)], verbose_name='pin'),
        ),
    ]
